-- Run this in the Supabase SQL Editor before enabling public reservations.
-- Usernames are held only after the user follows the email confirmation link.

create table if not exists public.username_reservations (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  username text not null unique check (username = lower(username) and username ~ '^[a-z0-9_]{3,20}$'),
  email text not null unique,
  intent text not null default 'fan' check (intent in ('fan', 'creator')),
  created_at timestamptz not null default now()
);

alter table public.username_reservations enable row level security;

create policy "Users can view their own reservation"
on public.username_reservations for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create their own reservation"
on public.username_reservations for insert
to authenticated
with check (
  auth.uid() = user_id
  and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

create or replace function public.username_available(candidate text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select candidate ~ '^[a-z0-9_]{3,20}$'
    and not exists (
      select 1 from public.username_reservations where username = lower(candidate)
    );
$$;

revoke all on function public.username_available(text) from public;
grant execute on function public.username_available(text) to anon, authenticated;

revoke all on public.username_reservations from anon;
grant select, insert on public.username_reservations to authenticated;
grant usage, select on sequence public.username_reservations_id_seq to authenticated;
